name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t EAZ-EAFIT/Tutorial6_EAZ:latest

      - name: Push image to Docker Hub
        run: docker push EAZ-EAFIT/Tutorial6_EAZ:latest
